version: "3"
services:
  myproxy:
    image: myjjproxy
    build: .
    ports:
      - "8082:8081"
    environment:
      - SECRET=a9ddbcaba8c0ac1a0a812dc0c2f08514b23f2db0a68343cb8199ebb38a6d91e4ebfb378e22ad39c2d01d0b4ec9c34aa91056862ddace3fbbd6852ee60c36acbf 
      - TARGETURL=https://postman-echo.com/post
      - HOST=0.0.0.0
    

